apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: skaffold-hv-microfrontends
build:
  artifacts:
    - image: skaffold-shell-service
      context: ./services/shell
      sync:
        infer:
          - "**/*.js"
    - image: skaffold-starships-service
      context: ./services/starships
      sync:
        infer:
          - "**/*.js"
deploy:
  kubectl:
    manifests:
      - ./services/shell/k8s-deployment.yaml
      - ./services/starships/k8s-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: shell-service
    port: 3000
  - resourceType: deployment
    resourceName: starships-service
    port: 3001
