apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-service
spec:
  selector:
    matchLabels:
      app: people-service
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
        - name: people-service
          image: skaffold-people-service
          ports:
            - containerPort: 3001
